apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: mazenr/node-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres 
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: blog_app
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
      volumes:
        - name: app-volume
          emptyDir: {}